### ISSUE TITLE
Add Oracle cloud provider

### ISSUE THREAD

**Issue by dgzlopes** [dgzlopes/cloud-detect#1]
Determine if the host cloud provider is Oracle.

You can see how we detect the other providers (e.g AWS) [here](https://github.com/dgzlopes/cloud-detect/tree/master/cloud_detect/providers).

For reference, you can check `banzaicloud/satellite` [code](https://github.com/banzaicloud/satellite/blob/master/providers/oracle.go).

**Comment by dennis-pg** [comment]
Would like to look into this

**Comment by dgzlopes** [comment]
Hi @dennis-pg! Thanks for your interest. Feel free to ping me if you need help.

**Comment by dennis-pg** [comment]
Hi @dgzlopes 

The file-based method looks okay. The metadata server based method does not seem to be working as per banzaicloud/satellite [code](https://github.com/banzaicloud/satellite/blob/master/providers/oracle.go) The link -> http://169.254.169.254/opc/v1/instance/metadata/ only contains an ssh key as mentioned in the [docs](https://docs.cloud.oracle.com/en-us/iaas/Content/Compute/Tasks/gettingmetadata.htm)

Do you want to use some other logic to determice if its is OCI from the response?

**Comment by dgzlopes** [comment]
Um, yeah, it only contains a list of ssh keys :neutral_face:

I'm not sure **why** Satellite is doing that, and well, I don't have experience with Oracle Cloud... So I would say, that for now, we can implement the file-based method - and it should work as expected.

We can leave the metadata approach for another issue. Might involve creating an Oracle account, spawning instances, testing things...

I kinda prefer `unknowns` that bad results :stuck_out_tongue_winking_eye:

**Comment by dgzlopes** [comment]
But probably some SSH key contains the string that Satellite checks (e.g Scaleway makes something similar).

**Comment by dennis-pg** [comment]
Have raised [PR](https://github.com/dgzlopes/cloud-detect/pull/6#partial-pull-merging)
