### ISSUE TITLE
Close file handlers on all check_vendor_file() methods

### ISSUE THREAD

**Issue by arossert** [dgzlopes/cloud-detect#13]
When reading the `self.vendor_file` the file is not closed, I will be happy to create a PR to use Path.read_text() instead of the `open()` call so the file will be closed.

**Comment by arossert** [comment]
Also it is a good idea to think of use `async` file operations with [aiofiles](https://pypi.org/project/aiofiles/) or [aiofile](https://pypi.org/project/aiofile/)

**Comment by kshivakumar** [comment]
@arossert Reading files is pretty quick since they are present(or absent) locally unlike api calls that have network latency. IMO it's not worth the effort to add additional dependencies and code complexity since the current speed is more than sufficient.

**Comment by arossert** [comment]
Would you accept the PR that wil close the file (using the read_text() function) ?

**Comment by arossert** [comment]
Created a PR #14 😃

**Comment by dgzlopes** [comment]
Thanks for the work folks! Closing this, as #14 has been merged.
