### ISSUE TITLE
Add Alibaba cloud provider

### ISSUE THREAD

**Issue by dgzlopes** [dgzlopes/cloud-detect#2]
Determine if the host cloud provider is Alibaba.

You can see how we detect the other providers (e.g AWS) [here](https://github.com/dgzlopes/cloud-detect/tree/master/cloud_detect/providers).

For reference, you can check `banzaicloud/satellite` [code](https://github.com/banzaicloud/satellite/blob/master/providers/alibaba.go).

**Comment by nmaltais** [comment]
I'll give this issue a go!

**Comment by rhyspowell** [comment]
Just dropped the PR in, should have possibly called it out earlier I was working on. Looks like tests are failing due to changes in pip that started today. Will see if I can resolve that in the branch

**Comment by rhyspowell** [comment]
PR #5 Is now good to look at, failing test is on one that I think you are happy with. Let me know if there is anything to fix
