### ISSUE TITLE
AWS IMDSv2 not supported

### ISSUE THREAD

**Issue by arossert** [dgzlopes/cloud-detect#27]
I have an issue that I'm getting 'unknown' even when on an `AWS` instance (windows).
It seems that the API for `http://169.254.169.254/latest/dynamic/instance-identity/document` is returning a 401 status code.

According to the documentation we need first to acquire a token and then to the call [instance-metadata-returns](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html#instance-metadata-returns)

You can look at this project to see how it is implemented in here https://pypi.org/project/ec2-metadata/

**Comment by arossert** [comment]
There are also some alternatives that I can think of, like looking to see if one of these directories exists 
* `C:\Program Files\Amazon`
* `C:\ProgramData\Amazon`

Also according to this https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/identify_ec2_instances.html, we can also use `wmic` to check if the UUID starts with EC2

**Comment by kshivakumar** [comment]
@arossert I think this package was never tested on Window VMs. [Even the CI only covers Ubuntu](https://github.com/dgzlopes/cloud-detect/blob/4f4068eb50aff547b845c8263aaf77925ca9241e/.github/workflows/tox.yml#L29).
It's highly probable it fails with other vendors as well.
I think Windows was never in the scope of this package(or the go package Satellite where it's inspired from). @dgzlopes can you confirm?

**Comment by arossert** [comment]
Since this lib is using the metadata API I will assume this can also happen in Linux if only V2 is supported.

**Comment by arossert** [comment]
@dgzlopes @kshivakumar Any suggestions on this issue? I'm using it to detect if running on cloud for multiple OS (Windows + Linux).
I can give some suggestions:
* Add support in V2. 
* Count `401` error as "success" since other cloud providers will probably not return 401 on this API call. 
* Add files detection for Windows locations. 

I'm willing to create a PR on any of these suggestions

If this module is only intended for Linux, it should be in the project details.

**Comment by arossert** [comment]
I created a pull request, can you consider adding this?

**Comment by kshivakumar** [comment]
Resolved by #28
